server {
    listen 80;

    resolver 127.0.0.11 valid=10s;

    location / {
        proxy_pass http://front-end:9000;
    }

    location /api {
        set $backend "back-end:5252";
        proxy_pass http://$backend;
    }
}
